services:
  frescos-api:
    container_name: frescos-api
    image: golang:latest
    volumes:
      - .:/usr/src/alkemy-g6
      - /go/pkg/mod:/go/pkg/mod
    ports:
     - 8080:8080
    depends_on:
    - frescos-db
    working_dir: /usr/src/alkemy-g6
    command: sh -c "sleep 1 && go run cmd/main.go"

  frescos-db:
    container_name: frescos-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frescos-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./docs/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  default:
    driver: bridge
    name: frescos-net